// angular_dotnet_lab/src/app/calculator/calculator.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.css']
})
export class CalculatorComponent {
  number1: number | null = null;
  number2: number | null = null;
  operator: string = 'add'; // Specify operator as a string
  result: number | null = null;

   onOperatorChange(event: Event): void {
    this.operator = (event.target as HTMLSelectElement).value;
  }
  calculate(): void {
    if(this.number1 === null || this.number2 === null) {
      this.result = null;
      return;
    }
    switch(this.operator) {
      case 'add':
        this.result = this.number1 + this.number2;
        break;
      case 'subtract':
        this.result = this.number1 - this.number2;
        break;
      case 'multiply':
        this.result = this.number1 * this.number2;
        break;
      default:
        console.log('Invalid operator!');
  }

}
}

<h1>Calculator</h1>
<form (ngSubmit)="calculate()">
  <label for="number1">Number 1:</label>
  <input type="number" id="number1" [(ngModel)]="number1" name="number1" />

  <label for="number2">Number 2:</label>
  <input type="number" id="number2" [(ngModel)]="number2" name="number2" />

  <label for="operator">Operator:</label>
  <select id="operator" [(ngModel)]="operator" name="operator">
    <option value="add">Add</option>
    <option value="subtract">Subtract</option>
    <option value="multiply">Multiply</option>
  </select>

  <button type="submit">Calculate</button>
</form>

<div *ngIf="result !== null">
  Result: {{ result }}
</div>

// react_dotnet_lab/src/Calculator.jsx
import React from 'react'
import { useState } from 'react'
const Calculator = () => {
    const [numbers, setNumbers] = useState({num1: 0, num2: 0,operator: '+'})
    const [result, setResult] = useState(0)
    const handleChange = (e) => {
       setNumbers({
            ...numbers,
            [e.target.name]: e.target.value
       })
    }
    const handleSubmit = (e) => {
        e.preventDefault()
        const {num1, num2,operator} = numbers
        console.log(num1, num2,operator)
        setResult(eval(`${num1} ${operator} ${num2}`))
    }

  return (
    <div className='calculator_container'>
        <h1>Calculator</h1>
        <form onSubmit={handleSubmit}>
            <input type="text" onChange={handleChange} name="num1" required placeholder="Enter first number" />
            <br />
            <input type="text" onChange={handleChange} name="num2" required placeholder="Enter second number" />
            <br />
            <select onChange={handleChange} name="operator">
                <option selected value="+">Add</option>
                <option value="-">Subtract</option>
                <option value="*">Multiply</option>
            </select>
            <button type="submit">Calculate</button>
        </form>
        <div className='result_display'>
            Result: <span>{result}</span>
        </div>
    </div>
  )
}
export default Calculator
